<a href="https://colab.research.google.com/github/lblogan14/python_data_analysis/blob/master/Chapter3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To install Numpy on Ubuntu systems, run

    sudo apt-get install python-numpy
 
The main object is ndarray (N-dimensional array).

The data type is specified by another NumPy object called dtype (data-type); each ndarray is associated with only one type of dtype.

The number of the dimensions and items in an array is deinfed by its shape, which is a tuple of N-positive intergers that specifies the size for each dimension. The dimensions are defined as axes and the number of axes are defined as rank.

Once you define the size of Numpy arrays at the time of createion, it remains unchanged whereas the Python lists can grow or shrink in size

In [0]:
import numpy as np

In [3]:
a = np.array([1,2,3]) #define a new ndarray by using array() function
print(a)
print(type(a)) #check the type of the object
a.dtype #check the data-type of the ndarray object

[1 2 3]
<class 'numpy.ndarray'>


dtype('int64')

the ndarray object, a, we just created, has one axis, and then its rank is 1, while its shape should be (3,1).

ndim is to get the axes;

size is to know the array length

shape is to get its shape

In [4]:
a.ndim

1

In [5]:
a.size

3

In [6]:
a.shape

(3,)

To create another array which has rank 2 (2 axes), each of axes has length 2

In [0]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim

2

In [12]:
b.size

4

In [13]:
b.shape

(2, 2)

**itemsize** atttribute is important because it defines the size in bytes of each item in the array

In [14]:
b.itemsize

8

**data** attribute is the buffer containing the actual elements of the array

In [15]:
b.data

##Create an Array

use array() function

In [18]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
type(c)

numpy.ndarray

array() also accepts tuples

In [21]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
type(d)

numpy.ndarray

array() also accepts mixed lists and tuples

In [24]:
e = np.array([(1,2,3),[4,5,6],(7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
type(e)

numpy.ndarray

## Types of Data

NumPy arrays can contain a wide variety of data types

In [26]:
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [27]:
g.dtype

dtype('<U1')

In [28]:
g.dtype.name #To get the data type name

'str32'

##The dtype Option

You can define the dtype using the dtype option as argument of the function

In [29]:
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

##Intrinsic Creation of an Array

###zeros() function

In [30]:
np.zeros((3,3)) #Note: (3,3) <--need the extra () enclosed to specify a 3-by-3 zero matrix 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros(3,3) #Error..

TypeError: ignored

###ones() function

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###arange() function

arange(start, stop(exclusive), step)

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,12,3) # start, end(exclusive), step

array([0, 3, 6, 9])

In [38]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

###reshape() function

divides a linear array in different parts in the manner specified by the shape argument

In [39]:
np.arange(0,12).reshape(3,4) # 3 rows, 4 columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###linspace() function

linspace(start, stop(exclusive), number of elements)

In [40]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

###random() function

in the numpy.random module

In [41]:
np.random.random(3)

array([0.94577888, 0.45133295, 0.82321372])

To create multidimensional array, pass the size of the array as an argument

In [42]:
np.random.random((3,4)) # 3 rows, 4 columns

array([[0.42112524, 0.88915592, 0.40795737, 0.07094062],
       [0.20584098, 0.12127782, 0.57058587, 0.02703768],
       [0.79277028, 0.92725591, 0.06362946, 0.66011857]])

##Arithmetic Operators

In [43]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [44]:
a+4

array([4, 5, 6, 7])

In [45]:
a*2 

array([0, 2, 4, 6])

Note the element-wise operations between two arrays:

In [46]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [47]:
a + b

array([ 4,  6,  8, 10])

In [48]:
a - b

array([-4, -4, -4, -4])

In [49]:
a * b

array([ 0,  5, 12, 21])

In [50]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [51]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

For multidimensional case

In [52]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

##Matrix Product

To perform the inner product, use dot() function

In [55]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Alternative way to use dot() function,

In [56]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Note the order matters...

In [57]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

##Increment and Decrement Operators

In [60]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [61]:
a += 1
a

array([1, 2, 3, 4])

In [62]:
a -= 1
a

array([0, 1, 2, 3])

In [63]:
a *= 2
a

array([0, 2, 4, 6])

##Universal Functions (ufunc)

In [64]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [65]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [66]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [67]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##Aggregate Functions

In [68]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [69]:
a.sum()

15.0

In [70]:
a.min()

0.3

In [71]:
a.max()

5.7

In [72]:
a.mean()

3.0

In [73]:
a.std()

2.0079840636817816

##Indexing, Slicing, and Iterating

###Indexing

In [74]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [75]:
a[4]

14

In [76]:
a[-1]

15

In [77]:
a[-6]

10

To select multiple items at once, pass the array of indices in square brackets

In [78]:
a[[1,3,4]]

array([11, 13, 14])

Two-dimensional case,

defined by two axes, where axis 0 is the row and axis 1 is the column.

Indexing should be a pair of values: first value is the index of the row and the second is the index of the column.

pass in the square brackets: [row index, coulmn index]

In [81]:
A = np.arange(10,19).reshape(3,3)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [82]:
A[1,2] #index starts with 0

15

###Slicing

In [83]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [84]:
a[1:5] #not include the last element

array([11, 12, 13, 14])

To skip a specific number of following items:

[start:stop:step]

In [85]:
a[1:5:2]

array([11, 13])

More examples

In [86]:
a[::2] #starts at index 0, stops at max index, skip 1 element

array([10, 12, 14])

In [87]:
a[:5:2] #starts at index 0, stops at index 5, skip 1 element

array([10, 12, 14])

In [88]:
a[:5:] #starts at index 0, stops at index 5, skip 0 element

array([10, 11, 12, 13, 14])

For two-dimensional array...

If you want to extract only the first row,

In [89]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [90]:
A[0,:] #slice at row 0 (first row)

array([10, 11, 12])

extract the first column,

In [91]:
A[:,0]

array([10, 13, 16])

If you want to extract a smaller matrix,

In [92]:
A[0:2, 0:2] #Note: from row 0 to row 1, from column 0 to column 1.. 

array([[10, 11],
       [13, 14]])

If you want to specify an array of indices,

In [93]:
A[[0,2], 0:2] # row 0 and row 2, from column 0 to column 1

array([[10, 11],
       [16, 17]])

###Iterating an Array

In [94]:
for i in a:
  print(i)

10
11
12
13
14
15


For two-dimensional array, didn't need nested for loop. Actually, if you apply the for loop to a matrix, it will always perform a scan according to the first axis

In [95]:
for row in A:
  print(row)

[10 11 12]
[13 14 15]
[16 17 18]


To make a iteration element by element, use the flat attribute on the matrix object...

In [96]:
A.flat #didn't show anything

In [97]:
for item in A.flat:
  print(item)

10
11
12
13
14
15
16
17
18


The **apply_along_axis()** function is used to launch an aggregate function that returns a value calculated for every single column or on every single row.

This function takes three arguments: the aggregate function, the axis on which to apply the iteration, and the array.

If axis=0, the iteration evaluates the elements column by column. (along axis 0 direction)

If axis=1, the iteration evaluates the elements row by row. (along axis 1 direction)

In [98]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [99]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [100]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

You can also use this function for user-defined function...

In [0]:
def foo(x):
  return x/2

In [102]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [103]:
np.apply_along_axis(foo, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

##Conditions and Boolean Arrays

Use the conditions and Boolean opearators to extract elements

In [104]:
A = np.random.random((4,4))
A

array([[0.97020641, 0.95864117, 0.57911306, 0.64145228],
       [0.85363744, 0.54708501, 0.52044195, 0.95844601],
       [0.64345674, 0.28272301, 0.32148098, 0.50902688],
       [0.52357658, 0.84178249, 0.92205502, 0.42988447]])

In [105]:
A < 0.5

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [106]:
A[A < 0.5]

array([0.28272301, 0.32148098, 0.42988447])

##Shape Manipulation
###reshape() fucntion

returns a new array and can be used to create new objects

In [107]:
a = np.random.random(12)
a

array([0.74336788, 0.36198068, 0.55231409, 0.96567228, 0.85496943,
       0.81360343, 0.27086975, 0.00815678, 0.13301364, 0.2202184 ,
       0.69077853, 0.05335147])

In [108]:
A = a.reshape(3,4)
A

array([[0.74336788, 0.36198068, 0.55231409, 0.96567228],
       [0.85496943, 0.81360343, 0.27086975, 0.00815678],
       [0.13301364, 0.2202184 , 0.69077853, 0.05335147]])

###shape attribute

If you want to modify the object without create a new object, use shape attribute to pass the tuple containing the new dimensions directly

In [110]:
a.shape = (3, 4) #Note: use TUPLE
a

array([[0.74336788, 0.36198068, 0.55231409, 0.96567228],
       [0.85496943, 0.81360343, 0.27086975, 0.00815678],
       [0.13301364, 0.2202184 , 0.69077853, 0.05335147]])

###ravel() function

Inverse operation: convert a two-dimensional array into a one-dimensional array

In [112]:
a = a.ravel()
a

array([0.74336788, 0.36198068, 0.55231409, 0.96567228, 0.85496943,
       0.81360343, 0.27086975, 0.00815678, 0.13301364, 0.2202184 ,
       0.69077853, 0.05335147])

In [114]:
a.shape = (12)
a

array([0.74336788, 0.36198068, 0.55231409, 0.96567228, 0.85496943,
       0.81360343, 0.27086975, 0.00815678, 0.13301364, 0.2202184 ,
       0.69077853, 0.05335147])

###transpose() function

In [116]:
A

array([[0.74336788, 0.36198068, 0.55231409, 0.96567228],
       [0.85496943, 0.81360343, 0.27086975, 0.00815678],
       [0.13301364, 0.2202184 , 0.69077853, 0.05335147]])

In [115]:
A.transpose()

array([[0.74336788, 0.85496943, 0.13301364],
       [0.36198068, 0.81360343, 0.2202184 ],
       [0.55231409, 0.27086975, 0.69077853],
       [0.96567228, 0.00815678, 0.05335147]])

##Array Manipulation
###Joining Arrays

merge multiple arrays to form a new one that contains all of the arrays

**vstack() function**

combines the second array as new rows of the first array. The array grows in a vertical direction.

In [119]:
A = np.ones((3,3))
B = np.zeros((3,3))
np.vstack((A,B)) #argument must be in tuple

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**hstack() function**

combines the second array as new columns of the first array. in horizontal direction

In [120]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

**column_stack()** and **row_stack()** are used with one-dimensional arrays

In [121]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
np.column_stack((a,b,c)) #arg must be tuple

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [122]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###Splitting Arrays

In [123]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**hsplit() function**

split the array horizontally, meaning the width of the array is divided into **2** parts

In [124]:
[B, C] = np.hsplit(A, 2) # second arg means to divide into 2 parts
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [125]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**vsplit() function**

split the array vertically, meaning the height of the array is divided into **2** parts

In [126]:
[B, C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [127]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**split() function**

allows you to split the array into nonsymmetrical parts

You also need to specify the indices of the parts to be divided

If axis = 0, the indices will be rows; if axis = 1, the indices will be columns.

For example, if you want to divide matrix A into three parts, the first of which is the first column, the second contains the second and the third column, and the third is the last column, you must specify in the following way:

In [128]:
[A1, A2, A3] = np.split(A, [1,3], axis = 1) # [1,3] means starting at index 1 and ending at index 2
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [129]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [130]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

Do the same thing by row:

In [131]:
[A1, A2, A3] = np.split(A, [1,3], axis=0)
A1

array([[0, 1, 2, 3]])

In [132]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
A3

array([[12, 13, 14, 15]])

##Copies or Views of Objects

The following assignments are just the views of the original array, not a copy!!

In [134]:
a = np.array([1,2,3,4])
b = a
b

array([1, 2, 3, 4])

In [135]:
a[2] = 0
b #change in a[2] changes b[2] as well

array([1, 2, 0, 4])

In [136]:
c = a[0:2]
c #slicing

array([1, 2])

In [137]:
a[0] = 0
c #change in a[0] changes c[0] as well

array([0, 2])

**copy() function** generates a complete and distinct array

In [138]:
a = np.array([1,2,3,4])
c = a.copy() #real copy
c

array([1, 2, 3, 4])

In [139]:
a[0] = 0
c #change in a[0] doesn't affect c[0]

array([1, 2, 3, 4])

##Brodadcasting

allows an operator or a function to act on two or mroe arrays to operate even if these arrays do not have the same shape

In [140]:
A = np.arange(16).reshape((4,4))
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [141]:
b

array([0, 1, 2, 3])

In [142]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

More complex case:

In [143]:
m = np.arange(6).reshape(3,1,2) # axis 0 has 3 elements, axis 1 has 1 row, axis 2 has 2 columns
m # 3 x 1 x 2

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [144]:
n = np.arange(6).reshape(3,2,1) # axis 0 has 3 elements, axis 1 has 2 rows, axis 2 has 1 column
n # 3 x 2 x 1

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [145]:
m + n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

##Structured Arrays

contains structs or records instead of individual items

In [146]:
structured = np.array([(1, 'First', 0.5, 1+2j), (2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)], dtype=('i2, a6, f4, c8'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

**dtype:**

bytes - b1

int - i1, i2, i4, i8

unsigned ints - u1, u2, u4, u8

floats - f2, f4, f8

complex - c8, c16

fixed length strings - a<n\>

You can also explicitly specify int8, uint8, float16, complex64...

In [147]:
structured = np.array([(1, 'First', 0.5, 1+2j), (2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)], dtype=('int16, a6, float32, complex64'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

Using the reference index to obtain the corresponding row:

In [148]:
structured[1]

(2, b'Second', 1.3, 2.-2.j)

The names, ('f0','f1','f2','f3'), assigned automatically can be used as the names of the columns of the arrays

In [149]:
structured['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [150]:
structured['f3']

array([1.+2.j, 2.-2.j, 1.+3.j], dtype=complex64)

To change the automatically assigned name, you can do it at the time of array declaration:

In [151]:
structured = np.array([(1, 'First', 0.5, 1+2j), (2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)], 
                      dtype=[('id', 'i2'), ('position', 'a6'), ('value', 'f4'), ('complex', 'c8')]) #dtype=[(name, datatype)]
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

Or you can redefine the tuples of names to dtype

In [152]:
structured.dtype.names = ('id', 'order', 'value', 'complex')
structured['order']

array([b'First', b'Second', b'Third'], dtype='|S6')

##Loading and Saving Data in Binary Files

###save()

The file wil automatically be given the .npy extension


In [157]:
data = np.random.random(12).reshape((4,3))
data

array([[0.1854912 , 0.82940777, 0.63597731],
       [0.5942558 , 0.41420995, 0.71631968],
       [0.51102291, 0.76612895, 0.44872904],
       [0.78301047, 0.27753672, 0.89593481]])

In [0]:
np.save('saved_data', data)

###load()

In [159]:
loaded_data = np.load('saved_data.npy')
loaded_data

array([[0.1854912 , 0.82940777, 0.63597731],
       [0.5942558 , 0.41420995, 0.71631968],
       [0.51102291, 0.76612895, 0.44872904],
       [0.78301047, 0.27753672, 0.89593481]])

##Reading Files with Tabular Data

When reading data from csv or txt files, you may want to use **getfromtxt('filename', delimiter=' , ', names=True)** to obtain a structured array, then you can access data by calling the names in the structured array